version: '3'

services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/api

    command: bash -c "python manage.py runserver 0.0.0.0:8000"


volumes:
  backend-data:
