# Generated by Django 4.1.4 on 2023-01-12 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=64)),
                ('img', models.ImageField(upload_to='shops1/images/shops')),
                ('address', models.CharField(default='some random address', max_length=150)),
                ('mobile', models.CharField(default='18519204393', max_length=11)),
                ('working_day', models.BooleanField(default=False)),
                ('business_time', models.CharField(default='From 10am to 12', max_length=150)),
                ('delivery_time', models.CharField(default='Between 15 to 20', max_length=70)),
                ('refundable', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops1.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
