# Generated by Django 3.2 on 2023-02-09 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts0', '0002_helporcontact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpOrContact',
        ),
    ]
