# Generated by Django 4.1.4 on 2023-01-12 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='My product', max_length=64)),
                ('description', models.TextField(default='This is some description')),
                ('quantity', models.IntegerField(default=1)),
                ('unit', models.CharField(choices=[('Kg', 'Kilogram'), ('L', 'Litre'), ('bottle', 'Bottle'), ('glass', 'Glass'), ('1 pc', 'Piece')], default='L', max_length=10)),
                ('img', models.ImageField(default='backend/products2/images/products/carrots.jpg', upload_to='products2/images/products')),
                ('price', models.DecimalField(decimal_places=1, default=650.5, max_digits=5)),
                ('new', models.BooleanField(blank=True, default=False, null=True)),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops1.category')),
                ('shop_owned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops1.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
