# Generated by Django 4.1.4 on 2023-01-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='products2/images/products/carrots.jpg', upload_to='products2/images/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Kg', 'Kilogram'), ('L', 'Litre'), ('Bottle', 'Bottle'), ('Glass', 'Glass'), ('Piece', 'Piece')], default='L', max_length=10),
        ),
    ]
