// User Authentication dispatch states
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const LOGOUT = 'LOGOUT';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
export const RESEND_ACTIVATION_SUCCESS = 'RESEND_ACTIVATION_SUCCESS';
export const RESEND_ACTIVATION_FAIL = 'RESEND_ACTIVATION_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
// user info
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';
export const PASSWORD_RESET_CONFIRM_SUCCESS = 'PASSWORD_RESET_CONFIRM_SUCCESS';
export const PASSWORD_RESET_CONFIRM_FAIL = 'PASSWORD_RESET_CONFIRM_FAIL';

export const EMAIL_RESET_SUCCESS = 'EMAIL_RESET_SUCCESS'
export const EMAIL_RESET_FAIL = 'EMAIL_RESET_FAIL'
export const EMAIL_RESET_CONFIRM_SUCCESS = 'EMAIL_RESET_CONFIRM_SUCCESS'
export const EMAIL_RESET_CONFIRM_FAIL = 'EMAIL_RESET_CONFIRM_FAIL'

// Social Auth Section
export const GOOGLE_AUTH_SUCCESS = 'GOOGLE_AUTH_SUCCESS';
export const GOOGLE_AUTH_FAIL = 'GOOGLE_AUTH_FAIL';
export const FACEBOOK_AUTH_SUCCESS = 'FACEBOOK_AUTH_SUCCESS';
export const FACEBOOK_AUTH_FAIL = 'FACEBOOK_AUTH_FAIL';

export const REFRESH_SUCCESS = 'REFRESH_SUCCESS'
export const REFRESH_FAIL = 'REFRESH_FAIL'

// Loading for User-Auth
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';

// User Profile
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAIL = 'GET_USER_PROFILE_FAIL';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_FAIL = 'UPDATE_USER_PROFILE_FAIL';
// Delete User
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';


// Alerts dispatch states
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';


// Categories
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';

// Loading for Categories
export const SET_CATEGORIES_LOADING = 'SET_CATEGORIES_LOADING';
export const REMOVE_CATEGORIES_LOADING = 'REMOVE_CATEGORIES_LOADING';

// Shops
export const GET_SHOPS_SUCCESS = 'GET_SHOPS_SUCCESS'
export const GET_SHOPS_FAIL = 'GET_SHOPS_FAIL';

// Loading for Shops
export const SET_SHOPS_LOADING = 'SET_SHOPS_LOADING';
export const REMOVE_SHOPS_LOADING = 'REMOVE_SHOPS_LOADING';


// Products
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';
// Loading for Products
export const SET_PRODUCTS_LOADING = 'SET_PRODUCTS_LOADING';
export const REMOVE_PRODUCTS_LOADING = 'REMOVE_PRODUCTS_LOADING';


// Local Cart
export const ADD_ITEM = 'ADD_ITEM';
export const GET_TOTAL = 'GET_TOTAL';
export const GET_ITEM_TOTAL = 'GET_ITEM_TOTAL';
export const GET_ITEMS = 'GET_ITEMS';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const EMPTY_CART = 'EMPTY_CART';

// Database Cart
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_FAIL = 'ADD_ITEM_FAIL';
export const GET_TOTAL_SUCCESS = 'GET_TOTAL_SUCCESS';
export const GET_TOTAL_FAIL = 'GET_TOTAL_FAIL';
export const GET_ITEM_TOTAL_SUCCESS = 'GET_ITEM_TOTAL_SUCCESS';
export const GET_ITEM_TOTAL_FAIL = 'GET_ITEM_TOTAL_FAIL';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAIL = 'GET_ITEMS_FAIL';
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';
export const UPDATE_ITEM_FAIL = 'UPDATE_ITEM_FAIL';
export const REMOVE_ITEM_SUCCESS = 'REMOVE_ITEM_SUCCESS';
export const REMOVE_ITEM_FAIL = 'REMOVE_ITEM_FAIL';
export const EMPTY_CART_SUCCESS = 'EMPTY_CART_SUCCESS';
export const EMPTY_CART_FAIL = 'EMPTY_CART_FAIL';
export const SYNCH_CART_SUCCESS = 'SYNCH_CART_SUCCESS';
export const SYNCH_CART_FAIL = 'SYNCH_CART_FAIL';


// orders - Checkout

// Get total price for order
export const GET_TOTAL_PRICE_SUCCESS = 'GET_TOTAL_PRICE_SUCCESS';
export const GET_TOTAL_PRICE_FAIL = 'GET_TOTAL_PRICE_FAIL';

// Create orders
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';

// Loading for creating orders
export const SET_CREATE_ORDER_LOADING = 'SET_CREATE_ORDER_LOADING';
export const REMOVE_CREATE_ORDER_LOADING = 'REMOVE_CREATE_ORDER_LOADING';

// Get orders after successfully create & detail
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAIL = 'GET_ORDERS_FAIL';

// for getting orders loading
export const SET_ORDERS_LOADING = 'SET_ORDERS_LOADING';
export const REMOVE_ORDERS_LOADING = 'REMOVE_ORDERS_LOADING';

// for one specific order detail
export const GET_ORDER_DETAIL_SUCCESS = 'GET_ORDER_DETAIL_SUCCESS';
export const GET_ORDER_DETAIL_FAIL = 'GET_ORDER_DETAIL_FAIL';
// cancel order
export const CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS';
export const CANCEL_ORDER_FAIL = 'CANCEL_ORDER_FAIL';


// Get Delivery Address
export const GET_DELIVERY_ADDRESS_SUCCESS = 'GET_DELIVERY_ADDRESS_SUCCESS';
export const GET_DELIVERY_ADDRESS_FAIL = 'GET_DELIVERY_ADDRESS_FAIL';

export const CREATE_DELIVERY_ADDRESS_SUCCESS = 'CREATE_DELIVERY_ADDRESS_SUCCESS';
export const CREATE_DELIVERY_ADDRESS_FAIL = 'CREATE_DELIVERY_ADDRESS_FAIL';

export const UPDATE_DELIVERY_ADDRESS_SUCCESS = 'UPDATE_DELIVERY_ADDRESS_SUCCESS';
export const UPDATE_DELIVERY_ADDRESS_FAIL = 'UPDATE_DELIVERY_ADDRESS_FAIL'

export const DELETE_DELIVERY_ADDRESS_SUCCESS = 'DELETE_DELIVERY_ADDRESS_SUCCESS';
export const DELETE_DELIVERY_ADDRESS_FAIL = 'DELETE_DELIVERY_ADDRESS_FAIL';

