# Generated by Django 4.1.4 on 2023-01-12 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery_address4', '0001_initial'),
        ('products2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('not_processed', 'Not Processed'), ('processed', 'Processed'), ('shipped', 'Shipping'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='not_processed', max_length=50)),
                ('unique_id', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', editable=False, length=13, max_length=13, prefix='', unique=True)),
                ('sub_total', models.DecimalField(decimal_places=1, max_digits=7)),
                ('delivery_fee', models.DecimalField(decimal_places=1, max_digits=7)),
                ('service_fee', models.DecimalField(decimal_places=1, max_digits=7)),
                ('total_amount', models.DecimalField(decimal_places=1, max_digits=9)),
                ('name', models.CharField(max_length=255)),
                ('delivery_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=11)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery_address4.deliveryaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=1, max_digits=5)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders5.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products2.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
