# Generated by Django 4.1.4 on 2023-01-12 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products2', '0001_initial'),
        ('orders5', '0002_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='products2.product'),
            preserve_default=False,
        ),
    ]
