# Generated by Django 3.2 on 2023-01-27 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders5', '0004_cancelorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service_fee',
        ),
    ]
